catalog /urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import home, contacts, product_detail

app_name = CatalogConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('contacts', contacts, name='contacts'),
    path("<int:pk>/product_detail/", product_detail, name="product_detail"),
]

config /urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
path('', include('catalog.urls', namespace='catalog'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog /models.py
from django.db import models
from django.utils import timezone

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Категория')
    description = models.TextField(verbose_name='Описание', **NULLABLE)

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'  # Настройка для наименования одного объекта
        verbose_name_plural = 'категории'  # Настройка для наименования набора объектов
        ordering = ('name',)


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование товара')
    description = models.TextField(**NULLABLE, verbose_name='Описание товара')
    item_pic = models.ImageField(upload_to="catalog/", verbose_name='Изображение товара', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    item_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена за единицу товара')
    created_date = models.DateField(auto_now_add=True, verbose_name='Дата внесения товара в базу', **NULLABLE)
    last_edited_date = models.DateField(auto_now=True, verbose_name='Дата последнего изменения', **NULLABLE)

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.name} {self.item_price} {self.category} '

    class Meta:
        verbose_name = 'товар'  # Настройка для наименования одного объекта
        verbose_name_plural = 'товары'  # Настройка для наименования набора объектов
        ordering = ('name', 'item_price')


class Contact(models.Model):
    name = models.CharField(max_length=40, verbose_name="Название компании", **NULLABLE)
    phone = models.CharField(max_length=20, verbose_name='Телефон', **NULLABLE)
    email = models.CharField(max_length=200, verbose_name='Имейл', **NULLABLE)
    address = models.TextField(verbose_name='Адрес', **NULLABLE)
    ind_number = models.CharField(max_length=30, verbose_name='ИНН', **NULLABLE)

    def __str__(self):
        # Строковое отображение объекта
        return f"{self.name}: {self.phone}, {self.email}, {self.address}, {self.ind_number}"

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'

catalog /views.py
from django.shortcuts import render

from catalog.models import Product, Contact, Category


def home(request):
    all_products = Product.objects.all()
    content = {
        'prod_to_display': all_products,
        'title': 'Best Store Ever'
    }
    return render(request, "catalog/home.html", content)


def contacts(request):
    company_info = Contact.objects.all()
    info_content = {
        'info_list': company_info,
        'title': 'Контакты'
    }
    if request.method == "POST":
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        message = request.POST.get("message")
        print(f"{name} ({phone}): {message}")
    return render(request, "catalog/contacts.html", info_content)


def product_detail(request, pk):
    one_product = Product.objects.filter(id=pk)
    content = {
        'prod_to_display': one_product,
        'title': 'Детальная информация о товаре'
    }
    return render(request, "catalog/product_detail.html", content)

catalog /templates/catalog /base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/inc_main_menu.html' %}

    {% block content %}
    {% endblock %}

<div class="container">

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                BestStoreEver
                <p>&copy; {% now 'Y' %} </p>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog /templates/catalog /contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>
<div class="container">
    <div class="row text-start">
        {% for info in info_list %}
            <div class="col-lg-9 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr>
                                <td class="w-25">Название компании</td>
                                <td>{{info.name|title}}</td>
                            </tr>
                            <tr>
                                <td class="w-25">Телефон</td>
                                <td>{{info.phone}}</td>
                            </tr>
                            <tr>
                                <td class="w-25">Имейл</td>
                                <td>{{info.email}}</td>
                            </tr>
                            <tr>
                                <td class="w-25">Адрес</td>
                                <td>{{info.address}}</td>
                            </tr>
                            <tr>
                                <td class="w-25">ИНН</td>
                                <td>{{info.ind_number}}</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="email">Имейл</label>
                            <input type="email" name="email" class="form-control" id="exampleInputEmail1" placeholder="Контактный имейл" required>
                        </div>
                         <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Ваше сообщение" required></textarea>
                        </div>
                        <button type="submit" value="Send" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog /templates/catalog /home.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">BestStoreEver</h1>
    <p class="lead">BestStoreEver - это самый удобный сервис по заказу продуктов онлайн</p>
</div>
<div class="container">
    <div class="row text-center">
        {% for prod in prod_to_display %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{prod.name}}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{prod.item_price}}</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{prod.category}}</li>
                        <li>- {{prod.description|truncatechars:10 }}</li>
                    </ul>
                    <a href="{% url 'catalog:product_detail' prod.pk %}"type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog /templates/catalog /includes /inc_main_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">BestStoreEver</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:home' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
    </nav>
</div>

catalog /templates/catalog /product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
  {% for prod in prod_to_display %}
  <div class="container">
      <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ prod.name }}</h4>
          </div>
          <img class="card-img-top"
               src="{{ prod.item_pic|mymedia }}"
               width="10"
               height="300"
               alt="Card image cap">
          <div class="card-body">
            <h1 class="card-title pricing-card-title">{{ prod.item_price }} </h1>
            <ul class="list-unstyled mt-3 mb-4">

              <li>Категория {{ prod.category }}</li>
              <p class="lead">Описание товара {{ prod.description }}</p>
              <li>Введен в продажу {{ prod.created_date }}</li>
              <li>Информация обновлена {{ prod.last_edited_date }}</li>

            </ul>
            <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
          </div>
        </div>
      </div>
     </div>
{% endfor %}

{% endblock %}